# Welcome to Agency Jekyll Theme!

# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
language: en
title: Nino Nhexie Kierulf
email: ninokierulf@gmail.com
description: > # this means to ignore newlines until "author:"
  [ntk]Site Description Here
author: ninokierulf
keyword: apple ios developer singapore 
baseurl: "" # the subpath of your site, e.g. /blog
url: https://ninokierulf.github.io
github_username:  ninokierulf
copyright: Nino Nhexie Kierulf &copy; 2017

start_year: 2011

# Build settings

markdown: kramdown
#permalink: pretty

#theme: agency-jekyll-theme #The "agency-jekyll-theme" is not supported by GitHub Pages. 

gems:
  - jekyll-feed
exclude:
  - agency-jekyll-theme.gemspec
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - screenshot.png
