url: https://ninokierulf.github.io
#baseurl: /agency-jekyll-theme/

# Site settings
title: Nino Nhexie Kierulf
email: ninokierulf@gmail.com
description: "[ntk] Site Description Here"
intro: "[ntk]Intro Hi. Welcome. Discover"
intro2: "[ntkIntro2 ]It's nice to meet you"
blogurl: "/blog"

privacy:
  title: "[ntk]Privacy Policy"
  url: "/privacy_policy"

terms:
  title: "[ntk]Terms of Use"
  url: "/terms_of_use"

start: 
  title: "[ntk]Tell Me More"
  url: "#portfolio"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fed136
  secondary: fec503  
  secondary-dark: 333

engage:
  title: "[ntk]Be Part <br>Of My <br>Story!"
  url: "#contact"

# Team names, titles and social links
# _data/people.yml

# Clients
# _data/client.yml

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
# _data/social.yml

# Postal address (add as many lines as necessary)
address:
  - line: In the land of the merlion
  - line: Singapore

# Build settings
markdown: kramdown
permalink: pretty

blog:
  title: "[ntk]Blog"
  description:

service:
  title: "[ntk]Services"
  description: "[ntk]Lorem what"

portfolio:
  title: "[ntk]Portfolio"
  description: "[ntk]Lorem ipsum dolor sit amet consectetur."

about:
  title: "[ntk]About"
  description: "[ntk]Lorem ipsum dolor sit amet consectetur."

contact:
  title: "[ntk]Contact Me"
  description: "[ntk]Lorem ipsum"
  entername: "[ntk]Your Name"
  enternamevalidation: "[ntk]Please enter your name."
  enteremail: "[ntk]Your Email"
  enteremailvalidation: "[ntk]Please enter your email address."
  enterphone: "[ntk]Your Phone"
  enterphonevalidation: "[ntk]Please enter your phone number."
  entermessage: "[ntk]Your Message"
  entermessagevalidation: "[ntk]Please enter your message."
  send: "Send Message"