- name: "Passionate"
  icon: "heart"
  description: "I love making apps that people use which enables them to be more productive."

- name: "Flexible"
  icon: "leaf"
  description: "I like learning new things, and because of this I can easily adapt to whatever is encountered."

- name: "Curious"
  icon: "question"
  description: "I always ask what's better, trying to improve myself and in the work I do. I also like to discover new technologies and ideas."
